### ISSUE TITLE
Include middleware in environments rather than config.ru

### ISSUE THREAD

**Issue by ACPK** [tylerhunt/rack-canonical-host#36]
Thoughts on following Thoughtbot's standards and including the line below in production.rb rather than config.ru?

https://github.com/thoughtbot/suspenders/blob/dd6b2037e5a7f5cd99b96187be143129af9ab2cb/lib/suspenders/app_builder.rb

    config.middleware.use Rack::CanonicalHost, ENV.fetch("APPLICATION_HOST")

**Comment by tylerhunt** [comment]
I use `config.ru` because I'm not a huge fan of the `config.middleware` approach, which tends to spread out the middleware configuration over several different files in the `config` directory. It also only applies to the Rails app, so if you have other endpoints mounted in Rack, they wouldn't be covered. There could be performance implications on the redirect requests, too, since the redirect wouldn't be processed until after the other Rails middleware, though this could be minimized by using `config.middleware.insert_before` to move it closer to the top of the stack. On the whole, it's mostly a matter of personal preference, and it should work just fine doing it the way Suspenders does.

**Comment by ACPK** [comment]
@tylerhunt Thanks!

**Comment by erikdahlstrand** [comment]
Just for information to someone trying to accomplish the same thing as I did...

If you for example want to include your domain in the [HSTS preload list](https://hstspreload.org) it's important that two separate redirects occur. First to the https protocol and then to your canonical host.

I.e.

    http://mysite.com  => https://mysite.com
    https://mysite.com => https://www.mysite.com

For this to happened in a Rails app you cannot use `config.ru` because SSL won't be the first redirection. As @tylerhunt mentions above, for performance reasons, you should insert the middleware close to the top but after the SSL middleware.

```
# config/environments/production.rb

...
  # Force all access to the app over SSL, use Strict-Transport-Security, and use secure cookies.
  config.force_ssl = true
  config.ssl_options = {
    hsts: { expires: 1.year, preload: true }
  }
...

  config.middleware.insert_after ActionDispatch::SSL,
                                 Rack::CanonicalHost,
                                 'www.mysite.com',
                                 cache_control: 'max-age=3600',
```
