### ISSUE TITLE
Forward non-canonical url in header

### ISSUE THREAD

**Issue by thechrisoshow** [tylerhunt/rack-canonical-host#45]
I would like to know what the non-canonical url was before redirecting to the canonical url, is this something that can be added to a header on redirect?

**Comment by tylerhunt** [comment]
This is not easily achievable due to the nature of how HTTP redirection works. Basically, a server response with a `Location` header tells the browser to make another request for that URL, but because this second request is made by the browser, it's not possible to set additional headers on it. The browser simply replays the original request headers when making that request, so additional headers added via Rack middleware won't be passed through.

You may be able to achieve this using cookies, but this isn't something that's likely to be added to this gem.

**Comment by thechrisoshow** [comment]
Ah, right. Thanks for letting me know.
